NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.bank.andongxu.link-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.bank.andongxu.link-cert.pem
    OrganizationalUnitIdentifier: peer
