NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.merchant.andongxu.link-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.merchant.andongxu.link-cert.pem
    OrganizationalUnitIdentifier: peer
